// Wrapper around the Emscripten-compiled SGP4 WASM module.
// Call initPropagator() once at startup, then use the exported functions.

let _mod = null

export async function initPropagator() {
  if (_mod) return _mod
  // Build the URL at runtime so Vite's static import-analysis plugin sees a
  // variable, not a resolvable literal, and skips resolution entirely.
  // sgp4.js lives in /public and is generated by cpp/build.ps1 — it is not
  // part of the JS module graph.
  const url = window.location.origin + '/sgp4.js'
  let factory
  try {
    ;({ default: factory } = await import(/* @vite-ignore */ url))
  } catch {
    throw new Error(
      'sgp4.js not found — build the WASM module first:\n  powershell -File cpp/build.ps1'
    )
  }
  _mod = await factory()
  return _mod
}

export function getPropagator() {
  if (!_mod) throw new Error('Propagator not initialized')
  return _mod
}

export function createSatrec(line1, line2) {
  return _mod.createSatrec(line1, line2) // returns int handle (0 = error)
}

export function freeSatrec(handle) { _mod.freeSatrec(handle) }
export function clearAll()         { _mod.clearAll() }

// Orbital period in minutes for a handle.
export function getPeriodMin(handle) { return _mod.getPeriodMin(handle) }

// Propagates every satellite handle in one WASM call.
//
// handles   Int32Array of handle ints, length N
// outView   Float64Array, length N*5 (pre-allocated, caller reuses each frame)
//           per satellite: [lat_rad, lon_rad, alt_m, speed_kms, valid(1/0)]
// Both arrays must be backed by WASM heap memory (allocated via _malloc below).
//
export function propagateBatch(handlesPtr, count, outPtr, timestampMs) {
  _mod.propagateBatch(timestampMs, handlesPtr, count, outPtr)
}

// Allocate N-slot handles buffer on the WASM heap. Returns { ptr, view }.
export function allocHandlesBuf(n) {
  const ptr  = _mod._malloc(n * 4)
  const view = new Int32Array(_mod.HEAP32.buffer, ptr, n)
  return { ptr, view }
}

// Allocate N-satellite output buffer on the WASM heap. Returns { ptr, view }.
export function allocOutBuf(n) {
  const ptr  = _mod._malloc(n * 5 * 8)
  const view = new Float64Array(_mod.HEAPF64.buffer, ptr, n * 5)
  return { ptr, view }
}

export function freeWasmBuf(ptr) { _mod._free(ptr) }

// Returns { valid, lat (rad), lon (rad), alt (km), speed (km/s) }
export function propagateOne(handle, timestampMs) {
  return _mod.propagateOne(handle, timestampMs)
}
